CREATE USER 'DMS_USER'@'%' IDENTIFIED BY 'DMS_USER';
GRANT ALTER, CREATE, DROP, INDEX, INSERT, UPDATE, DELETE, SELECT ON FLY1.* TO 'DMS_USER'@'%';
GRANT ALL PRIVILEGES ON awsdms_control.* TO 'DMS_USER'@'%';   
