insert into airport values ('AYPY', 'Port Moresby Jacksons International Airport',  146, 'POM');    
insert into airport values ('BIKF', 'Keflavik International Airport',  171, 'KEF');    
insert into airport values ('BKPR', 'PriÅ¡tina International Airport',  1789, 'PRN');    
insert into airport values ('CN-0083', 'Guodu air base',  0, '');    
insert into airport values ('CYEG', 'Edmonton International Airport',  2373, 'YEG');    
insert into airport values ('CYHZ', 'Halifax / Stanfield International Airport',  477, 'YHZ');    
insert into airport values ('CYOW', 'Ottawa Macdonald-Cartier International Airport',  374, 'YOW');    
insert into airport values ('CYUL', 'Montreal / Pierre Elliott Trudeau International Airport',  118, 'YUL');    
insert into airport values ('CYVR', 'Vancouver International Airport',  14, 'YVR');    
insert into airport values ('CYWG', 'Winnipeg / James Armstrong Richardson International Airport',  783, 'YWG');    
insert into airport values ('CYYC', 'Calgary International Airport',  3557, 'YYC');    
insert into airport values ('CYYJ', 'Victoria International Airport',  63, 'YYJ');    
insert into airport values ('CYYT', 'St. John's International Airport',  461, 'YYT');    
insert into airport values ('CYYZ', 'Lester B. Pearson International Airport',  569, 'YYZ');    
insert into airport values ('DAAG', 'Houari Boumediene Airport',  82, 'ALG');    
insert into airport values ('DFFD', 'Ouagadougou Airport',  1037, 'OUA');    
insert into airport values ('DGAA', 'Kotoka International Airport',  205, 'ACC');    
insert into airport values ('DNAA', 'Nnamdi Azikiwe International Airport',  1123, 'ABV');    
insert into airport values ('DNAI', 'Akwa Ibom International Airport',  170, 'QUO');    
insert into airport values ('DNKN', 'Mallam Aminu International Airport',  1562, 'KAN');    
insert into airport values ('DNMM', 'Murtala Muhammed International Airport',  135, 'LOS');    
insert into airport values ('DRRN', 'Diori Hamani International Airport',  732, 'NIM');    
insert into airport values ('DTTA', 'Tunis Carthage International Airport',  22, 'TUN');    
insert into airport values ('EBBR', 'Brussels Airport',  184, 'BRU');    
insert into airport values ('EBCI', 'Brussels South Charleroi Airport',  614, 'CRL');    
insert into airport values ('EBLG', 'LiÃ¨ge Airport',  659, 'LGG');    
insert into airport values ('EDDB', 'Berlin-SchÃ¶nefeld Airport',  157, 'SXF');    
insert into airport values ('EDDC', 'Dresden Airport',  755, 'DRS');    
insert into airport values ('EDDF', 'Frankfurt am Main Airport',  364, 'FRA');    
insert into airport values ('EDDG', 'MÃ¼nster OsnabrÃ¼ck Airport',  160, 'FMO');    
insert into airport values ('EDDH', 'Hamburg Airport',  53, 'HAM');    
insert into airport values ('EDDK', 'Cologne Bonn Airport',  302, 'CGN');    
insert into airport values ('EDDL', 'DÃ¼sseldorf Airport',  147, 'DUS');    
insert into airport values ('EDDM', 'Munich Airport',  1487, 'MUC');    
insert into airport values ('EDDN', 'Nuremberg Airport',  1046, 'NUE');    
insert into airport values ('EDDP', 'Leipzig/Halle Airport',  465, 'LEJ');    
insert into airport values ('EDDS', 'Stuttgart Airport',  1276, 'STR');    
insert into airport values ('EDDT', 'Berlin-Tegel Airport',  122, 'TXL');    
insert into airport values ('EDDV', 'Hannover Airport',  183, 'HAJ');    
insert into airport values ('EDDW', 'Bremen Airport',  14, 'BRE');    
insert into airport values ('EDLW', 'Dortmund Airport',  425, 'DTM');    
insert into airport values ('EDSB', 'Karlsruhe Baden-Baden Airport',  408, 'FKB');    
insert into airport values ('EETN', 'Lennart Meri Tallinn Airport',  131, 'TLL');    
insert into airport values ('EFHK', 'Helsinki Vantaa Airport',  179, 'HEL');    
insert into airport values ('EGAA', 'Belfast International Airport',  268, 'BFS');    
insert into airport values ('EGAC', 'George Best Belfast City Airport',  15, 'BHD');    
insert into airport values ('EGBB', 'Birmingham International Airport',  327, 'BHX');    
insert into airport values ('EGCC', 'Manchester Airport',  257, 'MAN');    
insert into airport values ('EGCN', 'Robin Hood Doncaster Sheffield Airport',  55, 'DSA');    
insert into airport values ('EGFF', 'Cardiff International Airport',  220, 'CWL');    
insert into airport values ('EGGD', 'Bristol Airport',  622, 'BRS');    
insert into airport values ('EGGP', 'Liverpool John Lennon Airport',  80, 'LPL');    
insert into airport values ('EGGW', 'London Luton Airport',  526, 'LTN');    
insert into airport values ('EGHH', 'Bournemouth Airport',  38, 'BOH');    
insert into airport values ('EGHI', 'Southampton Airport',  44, 'SOU');    
insert into airport values ('EGKK', 'London Gatwick Airport',  202, 'LGW');    
insert into airport values ('EGLL', 'London Heathrow Airport',  83, 'LHR');    
insert into airport values ('EGNM', 'Leeds Bradford Airport',  681, 'LBA');    
insert into airport values ('EGNT', 'Newcastle Airport',  266, 'NCL');    
insert into airport values ('EGNX', 'East Midlands Airport',  306, 'EMA');    
insert into airport values ('EGPD', 'Aberdeen Dyce Airport',  215, 'ABZ');    
insert into airport values ('EGPF', 'Glasgow International Airport',  26, 'GLA');    
insert into airport values ('EGPH', 'Edinburgh Airport',  135, 'EDI');    
insert into airport values ('EGSH', 'Norwich International Airport',  117, 'NWI');    
insert into airport values ('EGSS', 'London Stansted Airport',  348, 'STN');    
insert into airport values ('EGTE', 'Exeter International Airport',  102, 'EXT');    
insert into airport values ('EGUL', 'RAF Lakenheath',  32, 'LKZ');    
insert into airport values ('EGUN', 'RAF Mildenhall',  33, 'MHZ');    
insert into airport values ('EGVA', 'RAF Fairford',  286, 'FFD');    
insert into airport values ('EGVN', 'RAF Brize Norton',  288, 'BZZ');    
insert into airport values ('EHAM', 'Amsterdam Airport Schiphol',  -11, 'AMS');    
insert into airport values ('EHEH', 'Eindhoven Airport',  74, 'EIN');    
insert into airport values ('EICK', 'Cork Airport',  502, 'ORK');    
insert into airport values ('EIDW', 'Dublin Airport',  242, 'DUB');    
insert into airport values ('EINN', 'Shannon Airport',  46, 'SNN');    
insert into airport values ('EKBI', 'Billund Airport',  247, 'BLL');    
insert into airport values ('EKCH', 'Copenhagen Kastrup Airport',  17, 'CPH');    
insert into airport values ('EKYT', 'Aalborg Airport',  10, 'AAL');    
insert into airport values ('ELLX', 'Luxembourg-Findel International Airport',  1234, 'LUX');    
insert into airport values ('ENBO', 'BodÃ¸ Airport',  42, 'BOO');    
insert into airport values ('ENBR', 'Bergen Airport Flesland',  170, 'BGO');    
insert into airport values ('ENGM', 'Oslo Gardermoen Airport',  681, 'OSL');    
insert into airport values ('ENTC', 'TromsÃ¸ Airport',  31, 'TOS');    
insert into airport values ('ENVA', 'Trondheim Airport VÃ¦rnes',  56, 'TRD');    
insert into airport values ('ENZV', 'Stavanger Airport Sola',  29, 'SVG');    
insert into airport values ('EPGD', 'GdaÅsk Lech WaÅÄsa Airport',  489, 'GDN');    
insert into airport values ('EPKK', 'KrakÃ³w John Paul II International Airport',  791, 'KRK');    
insert into airport values ('EPKT', 'Katowice International Airport',  995, 'KTW');    
insert into airport values ('EPMO', 'Modlin Airport',  341, 'WMI');    
insert into airport values ('EPPO', 'PoznaÅ-Åawica Airport',  308, 'POZ');    
insert into airport values ('EPWA', 'Warsaw Chopin Airport',  362, 'WAW');    
insert into airport values ('EPWR', 'Copernicus WrocÅaw Airport',  404, 'WRO');    
insert into airport values ('ESGG', 'Gothenburg-Landvetter Airport',  506, 'GOT');    
insert into airport values ('ESMS', 'MalmÃ¶ Sturup Airport',  236, 'MMX');    
insert into airport values ('ESPA', 'LuleÃ¥ Airport',  65, 'LLA');    
insert into airport values ('ESSA', 'Stockholm-Arlanda Airport',  137, 'ARN');    
insert into airport values ('ETAR', 'Ramstein Air Base',  776, 'RMS');    
insert into airport values ('EVRA', 'Riga International Airport',  36, 'RIX');    
insert into airport values ('EYVI', 'Vilnius International Airport',  648, 'VNO');    
insert into airport values ('FACT', 'Cape Town International Airport',  151, 'CPT');    
insert into airport values ('FAGG', 'George Airport',  648, 'GRJ');    
insert into airport values ('FALE', 'King Shaka International Airport',  295, 'DUR');    
insert into airport values ('FAOR', 'OR Tambo International Airport',  5558, 'JNB');    
insert into airport values ('FBSK', 'Sir Seretse Khama International Airport',  3299, 'GBE');    
insert into airport values ('FDSK', 'King Mswati III International Airport',  1092, 'SHO');    
insert into airport values ('FIMP', 'Sir Seewoosagur Ramgoolam International Airport',  186, 'MRU');    
insert into airport values ('FLLS', 'Kenneth Kaunda International Airport',  3779, 'LUN');    
insert into airport values ('FMMI', 'Ivato Airport',  4198, 'TNR');    
insert into airport values ('FNLU', 'Quatro de Fevereiro Airport',  243, 'LAD');    
insert into airport values ('FQMA', 'Maputo Airport',  145, 'MPM');    
insert into airport values ('FSIA', 'Seychelles International Airport',  10, 'SEZ');    
insert into airport values ('FTTJ', 'N'Djamena International Airport',  968, 'NDJ');    
insert into airport values ('FVHA', 'Robert Gabriel Mugabe International Airport',  4887, 'HRE');    
insert into airport values ('FYWH', 'Hosea Kutako International Airport',  5640, 'WDH');    
insert into airport values ('FZAA', 'Ndjili International Airport',  1027, 'FIH');    
insert into airport values ('GABS', 'Modibo Keita International Airport',  1247, 'BKO');    
insert into airport values ('GCLA', 'La Palma Airport',  107, 'GCLA');    
insert into airport values ('GCLP', 'Gran Canaria Airport',  78, 'LPA');    
insert into airport values ('GCTS', 'Tenerife South Airport',  209, 'TFS');    
insert into airport values ('GCXO', 'Tenerife Norte Airport',  2076, 'TFN');    
insert into airport values ('GFLL', 'Lungi International Airport',  84, 'FNA');    
insert into airport values ('GLRB', 'Roberts International Airport',  31, 'ROB');    
insert into airport values ('GMMN', 'Mohammed V International Airport',  656, 'CMN');    
insert into airport values ('GOBD', 'Blaise Diagne International Airport',  290, 'DSS');    
insert into airport values ('GOOY', 'LÃ©opold SÃ©dar Senghor International Airport',  85, 'DKR');    
insert into airport values ('GQNO', 'NouakchottâOumtounsy International Airport',  9, 'NKC');    
insert into airport values ('GVAC', 'AmÃ­lcar Cabral International Airport',  177, 'SID');    
insert into airport values ('HAAB', 'Addis Ababa Bole International Airport',  7630, 'ADD');    
insert into airport values ('HCMH', 'Egal International Airport',  4471, 'HGA');    
insert into airport values ('HECA', 'Cairo International Airport',  382, 'CAI');    
insert into airport values ('HEGN', 'Hurghada International Airport',  52, 'HRG');    
insert into airport values ('HELX', 'Luxor International Airport',  294, 'LXR');    
insert into airport values ('HKJK', 'Jomo Kenyatta International Airport',  5330, 'NBO');    
insert into airport values ('HKMO', 'Mombasa Moi International Airport',  200, 'MBA');    
insert into airport values ('HLLT', 'Tripoli International Airport',  263, 'TIP');    
insert into airport values ('HRYR', 'Kigali International Airport',  4859, 'KGL');    
insert into airport values ('HSSJ', 'Juba International Airport',  1513, 'JUB');    
insert into airport values ('HSSS', 'Khartoum International Airport',  1265, 'KRT');    
insert into airport values ('HTDA', 'Julius Nyerere International Airport',  182, 'DAR');    
insert into airport values ('HTZA', 'Abeid Amani Karume International Airport',  54, 'ZNZ');    
insert into airport values ('HUEN', 'Entebbe International Airport',  3782, 'EBB');    
insert into airport values ('ID-0017', 'Aji Pangeran Tumenggung Pranoto International Airport',  73, 'AAP');    
insert into airport values ('KABQ', 'Albuquerque International Sunport',  5355, 'ABQ');    
insert into airport values ('KADW', 'Joint Base Andrews',  280, 'ADW');    
insert into airport values ('KAFW', 'Fort Worth Alliance Airport',  722, 'AFW');    
insert into airport values ('KAGS', 'Augusta Regional At Bush Field',  144, 'AGS');    
insert into airport values ('KAMA', 'Rick Husband Amarillo International Airport',  3607, 'AMA');    
insert into airport values ('KATL', 'Hartsfield Jackson Atlanta International Airport',  1026, 'ATL');    
insert into airport values ('KAUS', 'Austin Bergstrom International Airport',  542, 'AUS');    
insert into airport values ('KAVL', 'Asheville Regional Airport',  2165, 'AVL');    
insert into airport values ('KBAB', 'Beale Air Force Base',  113, 'BAB');    
insert into airport values ('KBAD', 'Barksdale Air Force Base',  166, 'BAD');    
insert into airport values ('KBDL', 'Bradley International Airport',  173, 'BDL');    
insert into airport values ('KBFI', 'Boeing Field King County International Airport',  21, 'BFI');    
insert into airport values ('KBGR', 'Bangor International Airport',  192, 'BGR');    
insert into airport values ('KBHM', 'Birmingham-Shuttlesworth International Airport',  650, 'BHM');    
insert into airport values ('KBIL', 'Billings Logan International Airport',  3652, 'BIL');    
insert into airport values ('KBLV', 'Scott AFB/Midamerica Airport',  459, 'BLV');    
insert into airport values ('KBMI', 'Central Illinois Regional Airport at Bloomington-Normal',  871, 'BMI');    
insert into airport values ('KBNA', 'Nashville International Airport',  599, 'BNA');    
insert into airport values ('KBOI', 'Boise Air Terminal/Gowen Field',  2871, 'BOI');    
insert into airport values ('KBOS', 'General Edward Lawrence Logan International Airport',  20, 'BOS');    
insert into airport values ('KBUF', 'Buffalo Niagara International Airport',  728, 'BUF');    
insert into airport values ('KBWI', 'Baltimore/Washington International Thurgood Marshall Airport',  146, 'BWI');    
insert into airport values ('KCAE', 'Columbia Metropolitan Airport',  236, 'CAE');    
insert into airport values ('KCBM', 'Columbus Air Force Base',  219, 'CBM');    
insert into airport values ('KCHA', 'Lovell Field',  683, 'CHA');    
insert into airport values ('KCHS', 'Charleston Air Force Base-International Airport',  46, 'CHS');    
insert into airport values ('KCID', 'The Eastern Iowa Airport',  869, 'CID');    
insert into airport values ('KCLE', 'Cleveland Hopkins International Airport',  791, 'CLE');    
insert into airport values ('KCLT', 'Charlotte Douglas International Airport',  748, 'CLT');    
insert into airport values ('KCMH', 'John Glenn Columbus International Airport',  815, 'CMH');    
insert into airport values ('KCOS', 'City of Colorado Springs Municipal Airport',  6187, 'COS');    
insert into airport values ('KCRP', 'Corpus Christi International Airport',  44, 'CRP');    
insert into airport values ('KCRW', 'Yeager Airport',  981, 'CRW');    
insert into airport values ('KCVG', 'Cincinnati Northern Kentucky International Airport',  896, 'CVG');    
insert into airport values ('KCVS', 'Cannon Air Force Base',  4295, 'CVS');    
insert into airport values ('KDAB', 'Daytona Beach International Airport',  34, 'DAB');    
insert into airport values ('KDAL', 'Dallas Love Field',  487, 'DAL');    
insert into airport values ('KDAY', 'James M Cox Dayton International Airport',  1009, 'DAY');    
insert into airport values ('KDBQ', 'Dubuque Regional Airport',  1077, 'DBQ');    
insert into airport values ('KDCA', 'Ronald Reagan Washington National Airport',  15, 'DCA');    
insert into airport values ('KDEN', 'Denver International Airport',  5431, 'DEN');    
insert into airport values ('KDFW', 'Dallas Fort Worth International Airport',  607, 'DFW');    
insert into airport values ('KDLF', 'DLF Airport',  1082, 'DLF');    
insert into airport values ('KDLH', 'Duluth International Airport',  1428, 'DLH');    
insert into airport values ('KDOV', 'Dover Air Force Base',  24, 'DOV');    
insert into airport values ('KDSM', 'Des Moines International Airport',  958, 'DSM');    
insert into airport values ('KDTW', 'Detroit Metropolitan Wayne County Airport',  645, 'DTW');    
insert into airport values ('KDYS', 'Dyess Air Force Base',  1789, 'DYS');    
insert into airport values ('KEDW', 'Edwards Air Force Base',  2312, 'EDW');    
insert into airport values ('KEND', 'Vance Air Force Base',  1307, 'END');    
insert into airport values ('KERI', 'Erie International Tom Ridge Field',  732, 'ERI');    
insert into airport values ('KEWR', 'Newark Liberty International Airport',  18, 'EWR');    
insert into airport values ('KFFO', 'Wright-Patterson Air Force Base',  823, 'FFO');    
insert into airport values ('KFLL', 'Fort Lauderdale Hollywood International Airport',  9, 'FLL');    
insert into airport values ('KFSM', 'Fort Smith Regional Airport',  469, 'FSM');    
insert into airport values ('KFTW', 'Fort Worth Meacham International Airport',  710, 'FTW');    
insert into airport values ('KFWA', 'Fort Wayne International Airport',  814, 'FWA');    
insert into airport values ('KGEG', 'Spokane International Airport',  2376, 'GEG');    
insert into airport values ('KGPT', 'Gulfport Biloxi International Airport',  28, 'GPT');    
insert into airport values ('KGRB', 'Austin Straubel International Airport',  695, 'GRB');    
insert into airport values ('KGSB', 'Seymour Johnson Air Force Base',  109, 'GSB');    
insert into airport values ('KGSO', 'Piedmont Triad International Airport',  925, 'GSO');    
insert into airport values ('KGSP', 'Greenville Spartanburg International Airport',  964, 'GSP');    
insert into airport values ('KGUS', 'Grissom Air Reserve Base',  812, 'GUS');    
insert into airport values ('KHIB', 'Range Regional Airport',  1354, 'HIB');    
insert into airport values ('KHMN', 'Holloman Air Force Base',  4093, 'HMN');    
insert into airport values ('KHOU', 'William P Hobby Airport',  46, 'HOU');    
insert into airport values ('KHSV', 'Huntsville International Carl T Jones Field',  629, 'HSV');    
insert into airport values ('KHTS', 'Tri-State/Milton J. Ferguson Field',  828, 'HTS');    
insert into airport values ('KIAD', 'Washington Dulles International Airport',  312, 'IAD');    
insert into airport values ('KIAH', 'George Bush Intercontinental Houston Airport',  97, 'IAH');    
insert into airport values ('KICT', 'Wichita Eisenhower National Airport',  1333, 'ICT');    
insert into airport values ('KIND', 'Indianapolis International Airport',  797, 'IND');    
insert into airport values ('KJAN', 'Jackson-Medgar Wiley Evers International Airport',  346, 'JAN');    
insert into airport values ('KJAX', 'Jacksonville International Airport',  30, 'JAX');    
insert into airport values ('KJFK', 'John F Kennedy International Airport',  13, 'JFK');    
insert into airport values ('KJLN', 'Joplin Regional Airport',  981, 'JLN');    
insert into airport values ('KLAS', 'McCarran International Airport',  2181, 'LAS');    
insert into airport values ('KLAX', 'Los Angeles International Airport',  125, 'LAX');    
insert into airport values ('KLBB', 'Lubbock Preston Smith International Airport',  3282, 'LBB');    
insert into airport values ('KLCK', 'Rickenbacker International Airport',  744, 'LCK');    
insert into airport values ('KLEX', 'Blue Grass Airport',  979, 'LEX');    
insert into airport values ('KLFI', 'Langley Air Force Base',  11, 'LFI');    
insert into airport values ('KLFT', 'Lafayette Regional Airport',  42, 'LFT');    
insert into airport values ('KLGA', 'La Guardia Airport',  21, 'LGA');    
insert into airport values ('KLIT', 'Bill Hillary Clinton National Airport/Adams Field',  262, 'LIT');    
insert into airport values ('KLTS', 'Altus Air Force Base',  1382, 'LTS');    
insert into airport values ('KLUF', 'Luke Air Force Base',  1085, 'LUF');    
insert into airport values ('KMBS', 'MBS International Airport',  668, 'MBS');    
insert into airport values ('KMCF', 'Mac Dill Air Force Base',  14, 'MCF');    
insert into airport values ('KMCI', 'Kansas City International Airport',  1026, 'MCI');    
insert into airport values ('KMCO', 'Orlando International Airport',  96, 'MCO');    
insert into airport values ('KMDW', 'Chicago Midway International Airport',  620, 'MDW');    
insert into airport values ('KMEM', 'Memphis International Airport',  341, 'MEM');    
insert into airport values ('KMGE', 'Dobbins Air Reserve Base',  1068, 'MGE');    
insert into airport values ('KMGM', 'Montgomery Regional (Dannelly Field) Airport',  221, 'MGM');    
insert into airport values ('KMHT', 'Manchester-Boston Regional Airport',  266, 'MHT');    
insert into airport values ('KMIA', 'Miami International Airport',  8, 'MIA');    
insert into airport values ('KMKE', 'General Mitchell International Airport',  723, 'MKE');    
insert into airport values ('KMLI', 'Quad City International Airport',  590, 'MLI');    
insert into airport values ('KMLU', 'Monroe Regional Airport',  79, 'MLU');    
insert into airport values ('KMOB', 'Mobile Regional Airport',  219, 'MOB');    
insert into airport values ('KMSN', 'Dane County Regional Truax Field',  887, 'MSN');    
insert into airport values ('KMSP', 'Minneapolis-St Paul International/Wold-Chamberlain Airport',  841, 'MSP');    
insert into airport values ('KMSY', 'Louis Armstrong New Orleans International Airport',  4, 'MSY');    
insert into airport values ('KMUO', 'Mountain Home Air Force Base',  2996, 'MUO');    
insert into airport values ('KOAK', 'Metropolitan Oakland International Airport',  9, 'OAK');    
insert into airport values ('KOKC', 'Will Rogers World Airport',  1295, 'OKC');    
insert into airport values ('KOMA', 'Eppley Airfield',  984, 'OMA');    
insert into airport values ('KONT', 'Ontario International Airport',  944, 'ONT');    
insert into airport values ('KORD', 'Chicago O'Hare International Airport',  672, 'ORD');    
insert into airport values ('KORF', 'Norfolk International Airport',  26, 'ORF');    
insert into airport values ('KPAM', 'Tyndall Air Force Base',  17, 'PAM');    
insert into airport values ('KPBI', 'Palm Beach International Airport',  19, 'PBI');    
insert into airport values ('KPDX', 'Portland International Airport',  31, 'PDX');    
insert into airport values ('KPHF', 'Newport News Williamsburg International Airport',  42, 'PHF');    
insert into airport values ('KPHL', 'Philadelphia International Airport',  36, 'PHL');    
insert into airport values ('KPHX', 'Phoenix Sky Harbor International Airport',  1135, 'PHX');    
insert into airport values ('KPIA', 'General Wayne A. Downing Peoria International Airport',  660, 'PIA');    
insert into airport values ('KPIT', 'Pittsburgh International Airport',  1203, 'PIT');    
insert into airport values ('KPVD', 'Theodore Francis Green State Airport',  55, 'PVD');    
insert into airport values ('KPWM', 'Portland International Jetport',  76, 'PWM');    
insert into airport values ('KRDU', 'Raleigh Durham International Airport',  435, 'RDU');    
insert into airport values ('KRFD', 'Chicago Rockford International Airport',  742, 'RFD');    
insert into airport values ('KRIC', 'Richmond International Airport',  167, 'RIC');    
insert into airport values ('KRND', 'Randolph Air Force Base',  761, 'RND');    
insert into airport values ('KRNO', 'Reno Tahoe International Airport',  4415, 'RNO');    
insert into airport values ('KROA', 'RoanokeâBlacksburg Regional Airport',  1175, 'ROA');    
insert into airport values ('KROC', 'Greater Rochester International Airport',  559, 'ROC');    
insert into airport values ('KRST', 'Rochester International Airport',  1317, 'RST');    
insert into airport values ('KRSW', 'Southwest Florida International Airport',  30, 'RSW');    
insert into airport values ('KSAN', 'San Diego International Airport',  17, 'SAN');    
insert into airport values ('KSAT', 'San Antonio International Airport',  809, 'SAT');    
insert into airport values ('KSAV', 'Savannah Hilton Head International Airport',  50, 'SAV');    
insert into airport values ('KSBN', 'South Bend Regional Airport',  799, 'SBN');    
insert into airport values ('KSDF', 'Louisville Muhammad Ali International Airport',  501, 'SDF');    
insert into airport values ('KSEA', 'Seattle Tacoma International Airport',  433, 'SEA');    
insert into airport values ('KSFB', 'Orlando Sanford International Airport',  55, 'SFB');    
insert into airport values ('KSFO', 'San Francisco International Airport',  13, 'SFO');    
insert into airport values ('KSGF', 'Springfield Branson National Airport',  1268, 'SGF');    
insert into airport values ('KSJC', 'Norman Y. Mineta San Jose International Airport',  62, 'SJC');    
insert into airport values ('KSKA', 'Fairchild Air Force Base',  2461, 'SKA');    
insert into airport values ('KSLC', 'Salt Lake City International Airport',  4227, 'SLC');    
insert into airport values ('KSMF', 'Sacramento International Airport',  27, 'SMF');    
insert into airport values ('KSNA', 'John Wayne Airport-Orange County Airport',  56, 'SNA');    
insert into airport values ('KSPI', 'Abraham Lincoln Capital Airport',  598, 'SPI');    
insert into airport values ('KSPS', 'Sheppard Air Force Base-Wichita Falls Municipal Airport',  1019, 'SPS');    
insert into airport values ('KSRQ', 'Sarasota Bradenton International Airport',  30, 'SRQ');    
insert into airport values ('KSSC', 'Shaw Air Force Base',  241, 'SSC');    
insert into airport values ('KSTL', 'St Louis Lambert International Airport',  618, 'STL');    
insert into airport values ('KSUS', 'Spirit of St Louis Airport',  463, 'SUS');    
insert into airport values ('KSUU', 'Travis Air Force Base',  62, 'SUU');    
insert into airport values ('KSUX', 'Sioux Gateway Airport/Brigadier General Bud Day Field',  1098, 'SUX');    
insert into airport values ('KSYR', 'Syracuse Hancock International Airport',  421, 'SYR');    
insert into airport values ('KSZL', 'Whiteman Air Force Base',  870, 'SZL');    
insert into airport values ('KTCM', 'McChord Air Force Base',  322, 'TCM');    
insert into airport values ('KTIK', 'Tinker Air Force Base',  1291, 'TIK');    
insert into airport values ('KTLH', 'Tallahassee Regional Airport',  81, 'TLH');    
insert into airport values ('KTOL', 'Toledo Express Airport',  683, 'TOL');    
insert into airport values ('KTPA', 'Tampa International Airport',  26, 'TPA');    
insert into airport values ('KTRI', 'Tri-Cities Regional TN/VA Airport',  1519, 'TRI');    
insert into airport values ('KTUL', 'Tulsa International Airport',  677, 'TUL');    
insert into airport values ('KTUS', 'Tucson International Airport / Morris Air National Guard Base',  2643, 'TUS');    
insert into airport values ('KTYS', 'McGhee Tyson Airport',  981, 'TYS');    
insert into airport values ('KVBG', 'Vandenberg Air Force Base',  369, 'VBG');    
insert into airport values ('KVPS', 'Destin-Ft Walton Beach Airport',  87, 'VPS');    
insert into airport values ('KWRB', 'Robins Air Force Base',  294, 'WRB');    
insert into airport values ('LATI', 'Tirana International Airport Mother Teresa',  126, 'TIA');    
insert into airport values ('LBBG', 'Burgas Airport',  135, 'BOJ');    
insert into airport values ('LBSF', 'Sofia Airport',  1742, 'SOF');    
insert into airport values ('LBWN', 'Varna Airport',  230, 'VAR');    
insert into airport values ('LCLK', 'Larnaca International Airport',  8, 'LCA');    
insert into airport values ('LCPH', 'Paphos International Airport',  41, 'PFO');    
insert into airport values ('LCRA', 'RAF Akrotiri',  76, 'AKT');    
insert into airport values ('LDZA', 'Zagreb Airport',  353, 'ZAG');    
insert into airport values ('LEAL', 'Alicante International Airport',  142, 'ALC');    
insert into airport values ('LEBL', 'Barcelona International Airport',  12, 'BCN');    
insert into airport values ('LEMD', 'Adolfo SuÃ¡rez MadridâBarajas Airport',  1998, 'MAD');    
insert into airport values ('LEMG', 'MÃ¡laga Airport',  53, 'AGP');    
insert into airport values ('LEPA', 'Palma De Mallorca Airport',  27, 'PMI');    
insert into airport values ('LEST', 'Santiago de Compostela Airport',  1213, 'SCQ');    
insert into airport values ('LFBD', 'Bordeaux-MÃ©rignac Airport',  162, 'BOD');    
insert into airport values ('LFBO', 'Toulouse-Blagnac Airport',  499, 'TLS');    
insert into airport values ('LFLL', 'Lyon Saint-ExupÃ©ry Airport',  821, 'LYS');    
insert into airport values ('LFML', 'Marseille Provence Airport',  74, 'MRS');    
insert into airport values ('LFMN', 'Nice-CÃ´te d'Azur Airport',  12, 'NCE');    
insert into airport values ('LFOA', 'Avord (BA 702) Air Base',  580, '');    
insert into airport values ('LFPG', 'Charles de Gaulle International Airport',  392, 'CDG');    
insert into airport values ('LFPO', 'Paris-Orly Airport',  291, 'ORY');    
insert into airport values ('LFSB', 'EuroAirport Basel-Mulhouse-Freiburg Airport',  885, 'BSL');    
insert into airport values ('LGAV', 'Eleftherios Venizelos International Airport',  308, 'ATH');    
insert into airport values ('LGIR', 'Heraklion International Nikos Kazantzakis Airport',  115, 'HER');    
insert into airport values ('LGTS', 'Thessaloniki Macedonia International Airport',  22, 'SKG');    
insert into airport values ('LHBP', 'Budapest Liszt Ferenc International Airport',  495, 'BUD');    
insert into airport values ('LIBD', 'Bari Karol WojtyÅa Airport',  177, 'BRI');    
insert into airport values ('LICC', 'Catania-Fontanarossa Airport',  39, 'CTA');    
insert into airport values ('LICJ', 'FalconeâBorsellino Airport',  65, 'PMO');    
insert into airport values ('LIEE', 'Cagliari Elmas Airport',  13, 'CAG');    
insert into airport values ('LIMC', 'Malpensa International Airport',  768, 'MXP');    
insert into airport values ('LIME', 'Il Caravaggio International Airport',  782, 'BGY');    
insert into airport values ('LIMF', 'Turin Airport',  989, 'TRN');    
insert into airport values ('LIMJ', 'Genoa Cristoforo Colombo Airport',  13, 'GOA');    
insert into airport values ('LIML', 'Milano Linate Airport',  353, 'LIN');    
insert into airport values ('LIPE', 'Bologna Guglielmo Marconi Airport',  123, 'BLQ');    
insert into airport values ('LIPH', 'Treviso-Sant'Angelo Airport',  59, 'TSF');    
insert into airport values ('LIPX', 'Verona Villafranca Airport',  239, 'VRN');    
insert into airport values ('LIPZ', 'Venice Marco Polo Airport',  7, 'VCE');    
insert into airport values ('LIRA', 'CiampinoâG. B. Pastine International Airport',  427, 'CIA');    
insert into airport values ('LIRF', 'Leonardo da VinciâFiumicino Airport',  13, 'FCO');    
insert into airport values ('LIRN', 'Naples International Airport',  294, 'NAP');    
insert into airport values ('LIRP', 'Pisa International Airport',  6, 'PSA');    
insert into airport values ('LJLJ', 'Ljubljana JoÅ¾e PuÄnik Airport',  1273, 'LJU');    
insert into airport values ('LKPR', 'VÃ¡clav Havel Airport Prague',  1247, 'PRG');    
insert into airport values ('LLBG', 'Ben Gurion International Airport',  135, 'TLV');    
insert into airport values ('LLOV', 'Ovda International Airport',  1492, 'VDA');    
insert into airport values ('LMML', 'Malta International Airport',  300, 'MLA');    
insert into airport values ('LOWW', 'Vienna International Airport',  600, 'VIE');    
insert into airport values ('LPFR', 'Faro Airport',  24, 'FAO');    
insert into airport values ('LPLA', 'Lajes Airport',  180, 'TER');    
insert into airport values ('LPPD', 'JoÃ£o Paulo II Airport',  259, 'PDL');    
insert into airport values ('LPPR', 'Francisco de SÃ¡ Carneiro Airport',  228, 'OPO');    
insert into airport values ('LPPT', 'Humberto Delgado Airport (Lisbon Portela Airport)',  374, 'LIS');    
insert into airport values ('LQSA', 'Sarajevo International Airport',  1708, 'SJJ');    
insert into airport values ('LROP', 'Henri CoandÄ International Airport',  314, 'OTP');    
insert into airport values ('LSGG', 'Geneva Cointrin International Airport',  1411, 'GVA');    
insert into airport values ('LSZH', 'ZÃ¼rich Airport',  1416, 'ZRH');    
insert into airport values ('LTAC', 'EsenboÄa International Airport',  3125, 'ESB');    
insert into airport values ('LTAF', 'Adana Airport',  65, 'ADA');    
insert into airport values ('LTAI', 'Antalya International Airport',  177, 'AYT');    
insert into airport values ('LTAJ', 'Gaziantep International Airport',  2315, 'GZT');    
insert into airport values ('LTBA', 'AtatÃ¼rk International Airport',  163, 'ISL');    
insert into airport values ('LTBJ', 'Adnan Menderes International Airport',  412, 'ADB');    
insert into airport values ('LTBS', 'Dalaman International Airport',  20, 'DLM');    
insert into airport values ('LTCE', 'Erzurum International Airport',  5763, 'ERZ');    
insert into airport values ('LTCG', 'Trabzon International Airport',  104, 'TZX');    
insert into airport values ('LTFC', 'SÃ¼leyman Demirel International Airport',  2835, 'ISE');    
insert into airport values ('LTFE', 'Milas Bodrum International Airport',  21, 'BJV');    
insert into airport values ('LTFJ', 'Sabiha GÃ¶kÃ§en International Airport',  312, 'SAW');    
insert into airport values ('LTFM', 'Istanbul Airport',  325, 'IST');    
insert into airport values ('LWSK', 'Skopje International Airport',  781, 'SKP');    
insert into airport values ('LYBE', 'Belgrade Nikola Tesla Airport',  335, 'BEG');    
insert into airport values ('LYPG', 'Podgorica Airport',  141, 'TGD');    
insert into airport values ('LZIB', 'M. R. Å tefÃ¡nik Airport',  436, 'BTS');    
insert into airport values ('MDPC', 'Punta Cana International Airport',  47, 'PUJ');    
insert into airport values ('MDSD', 'Las AmÃ©ricas International Airport',  59, 'SDQ');    
insert into airport values ('MGGT', 'La Aurora Airport',  4952, 'GUA');    
insert into airport values ('MKJP', 'Norman Manley International Airport',  10, 'KIN');    
insert into airport values ('MMAA', 'General Juan N Alvarez International Airport',  16, 'ACA');    
insert into airport values ('MMGL', 'Don Miguel Hidalgo Y Costilla International Airport',  5016, 'GDL');    
insert into airport values ('MMHO', 'General Ignacio P. Garcia International Airport',  627, 'HMO');    
insert into airport values ('MMMX', 'Licenciado Benito Juarez International Airport',  7316, 'MEX');    
insert into airport values ('MMMY', 'General Mariano Escobedo International Airport',  1278, 'MTY');    
insert into airport values ('MMPR', 'Licenciado Gustavo DÃ­az Ordaz International Airport',  23, 'PVR');    
insert into airport values ('MMSD', 'Los Cabos International Airport',  374, 'SJD');    
insert into airport values ('MMTJ', 'General Abelardo L. RodrÃ­guez International Airport',  489, 'TIJ');    
insert into airport values ('MMUN', 'CancÃºn International Airport',  22, 'CUN');    
insert into airport values ('MPTO', 'Tocumen International Airport',  135, 'PTY');    
insert into airport values ('MRLB', 'Daniel Oduber Quiros International Airport',  270, 'LIR');    
insert into airport values ('MSLP', 'MonseÃ±or Ãscar Arnulfo Romero International Airport',  101, 'SAL');    
insert into airport values ('MUHA', 'JosÃ© MartÃ­ International Airport',  210, 'HAV');    
insert into airport values ('MUVR', 'Juan Gualberto Gomez International Airport',  210, 'VRA');    
insert into airport values ('MWCR', 'Owen Roberts International Airport',  8, 'GCM');    
insert into airport values ('MYNN', 'Lynden Pindling International Airport',  16, 'NAS');    
insert into airport values ('MZBZ', 'Philip S. W. Goldson International Airport',  15, 'BZE');    
insert into airport values ('NCRG', 'Rarotonga International Airport',  19, 'RAR');    
insert into airport values ('NTAA', 'Faa'a International Airport',  5, 'PPT');    
insert into airport values ('NZAA', 'Auckland International Airport',  23, 'AKL');    
insert into airport values ('NZCH', 'Christchurch International Airport',  123, 'CHC');    
insert into airport values ('NZWN', 'Wellington International Airport',  41, 'WLG');    
insert into airport values ('OBBI', 'Bahrain International Airport',  6, 'BAH');    
insert into airport values ('OEDF', 'King Fahd International Airport',  72, 'DMM');    
insert into airport values ('OEDR', 'King Abdulaziz Air Base',  84, 'DHA');    
insert into airport values ('OEJN', 'King Abdulaziz International Airport',  48, 'JED');    
insert into airport values ('OEMA', 'Prince Mohammad Bin Abdulaziz Airport',  2151, 'MED');    
insert into airport values ('OERK', 'King Khaled International Airport',  2049, 'RUH');    
insert into airport values ('OIIE', 'Imam Khomeini International Airport',  3305, 'IKA');    
insert into airport values ('OIII', 'Mehrabad International Airport',  3962, 'THR');    
insert into airport values ('OIMM', 'Mashhad International Airport',  3263, 'MHD');    
insert into airport values ('OISS', 'Shiraz Shahid Dastghaib International Airport',  4927, 'SYZ');    
insert into airport values ('OITT', 'Tabriz International Airport',  4459, 'TBZ');    
insert into airport values ('OJAI', 'Queen Alia International Airport',  2395, 'AMM');    
insert into airport values ('OKBK', 'Kuwait International Airport',  206, 'KWI');    
insert into airport values ('OLBA', 'Beirut Rafic Hariri International Airport',  87, 'BEY');    
insert into airport values ('OM-0003', 'Duqm International Airport',  364, 'DQM');    
insert into airport values ('OM-0004', 'Rustaq Airport',  349, 'MNH');    
insert into airport values ('OMAA', 'Abu Dhabi International Airport',  88, 'AUH');    
insert into airport values ('OMDB', 'Dubai International Airport',  62, 'DXB');    
insert into airport values ('OMDW', 'Al Maktoum International Airport',  114, 'DWC');    
insert into airport values ('OMSJ', 'Sharjah International Airport',  111, 'SHJ');    
insert into airport values ('OOMS', 'Muscat International Airport',  48, 'MCT');    
insert into airport values ('OPIS', 'Islamabad International Airport',  1761, 'ISB');    
insert into airport values ('OPST', 'Sialkot Airport',  837, 'SKT');    
insert into airport values ('ORBI', 'Baghdad International Airport',  114, 'BGW');    
insert into airport values ('ORMM', 'Basrah International Airport',  11, 'BSR');    
insert into airport values ('OSAP', 'Aleppo International Airport',  1276, 'ALP');    
insert into airport values ('OSDI', 'Damascus International Airport',  2020, 'DAM');    
insert into airport values ('OSLK', 'Bassel Al-Assad International Airport',  157, 'LTK');    
insert into airport values ('OTHH', 'Hamad International Airport',  13, 'DOH');    
insert into airport values ('PAFA', 'Fairbanks International Airport',  439, 'FAI');    
insert into airport values ('PANC', 'Ted Stevens Anchorage International Airport',  152, 'ANC');    
insert into airport values ('PGUM', 'Antonio B. Won Pat International Airport',  298, 'PGUM');    
insert into airport values ('PH-0001', 'Laguindingan Airport',  190, 'CGY');    
insert into airport values ('PH-0073', 'Northern Cagayan International Airport',  0, '');    
insert into airport values ('PHNL', 'Daniel K Inouye International Airport',  13, 'HNL');    
insert into airport values ('QA-0001', 'Tamim Airbase',  0, '');    
insert into airport values ('RCBS', 'Kinmen Airport',  93, 'KNH');    
insert into airport values ('RCKH', 'Kaohsiung International Airport',  31, 'KHH');    
insert into airport values ('RCTP', 'Taiwan Taoyuan International Airport',  106, 'TPE');    
insert into airport values ('RJAA', 'Narita International Airport',  141, 'NRT');    
insert into airport values ('RJBB', 'Kansai International Airport',  26, 'KIX');    
insert into airport values ('RJCC', 'New Chitose Airport',  82, 'CTS');    
insert into airport values ('RJFF', 'Fukuoka Airport',  32, 'FUK');    
insert into airport values ('RJFK', 'Kagoshima Airport',  906, 'KOJ');    
insert into airport values ('RJGG', 'Chubu Centrair International Airport',  15, 'NGO');    
insert into airport values ('rjns', 'Mt. Fuji Shizuoka Airport',  433, 'FSZ');    
insert into airport values ('RJOO', 'Osaka International Airport',  50, 'ITM');    
insert into airport values ('RJTT', 'Tokyo Haneda International Airport',  35, 'RJTT');    
insert into airport values ('RJTY', 'Yokota Air Base',  463, 'OKO');    
insert into airport values ('RKJB', 'Muan International Airport',  35, 'MWX');    
insert into airport values ('RKJK', 'Kunsan Air Base',  29, 'KUV');    
insert into airport values ('RKPC', 'Jeju International Airport',  118, 'CJU');    
insert into airport values ('RKPK', 'Gimhae International Airport',  6, 'PUS');    
insert into airport values ('RKSI', 'Incheon International Airport',  23, 'ICN');    
insert into airport values ('RKSO', 'Osan Air Base',  38, 'OSN');    
insert into airport values ('RKSS', 'Gimpo International Airport',  59, 'GMP');    
insert into airport values ('RKTU', 'Cheongju International Airport/Cheongju Air Base (K-59/G-513)',  191, 'CJJ');    
insert into airport values ('ROAH', 'Naha Airport',  12, 'OKA');    
insert into airport values ('RODN', 'Kadena Air Base',  143, 'DNA');    
insert into airport values ('RPLC', 'Diosdado Macapagal International Airport',  484, 'CRK');    
insert into airport values ('RPLL', 'Ninoy Aquino International Airport',  75, 'RPLL');    
insert into airport values ('RPMD', 'Francisco Bangoy International Airport',  96, 'DVO');    
insert into airport values ('RPVM', 'Mactan Cebu International Airport',  31, 'CEB');    
insert into airport values ('RU-0016', 'Lipetsk Air Base',  636, '');    
insert into airport values ('RU-0035', 'Grozny North Airport',  548, 'GRV');    
insert into airport values ('RU-2244', 'Ukrainka Air Base',  771, '');    
insert into airport values ('RU-4464', 'Olenya Air Base',  702, '');    
insert into airport values ('SA-0009', 'Financial Services business and personal loans no collateral require',  0, '');    
insert into airport values ('SAEZ', 'Ministro Pistarini International Airport',  67, 'EZE');    
insert into airport values ('SBBE', 'Val de Cans/JÃºlio Cezar Ribeiro International Airport',  54, 'BEL');    
insert into airport values ('SBBR', 'Presidente Juscelino Kubistschek International Airport',  3497, 'BSB');    
insert into airport values ('SBCF', 'Tancredo Neves International Airport',  2715, 'CNF');    
insert into airport values ('SBCT', 'Afonso Pena Airport',  2988, 'CWB');    
insert into airport values ('SBEG', 'Eduardo Gomes International Airport',  264, 'MAO');    
insert into airport values ('SBFL', 'HercÃ­lio Luz International Airport',  16, 'FLN');    
insert into airport values ('SBGL', 'Rio GaleÃ£o â Tom Jobim International Airport',  28, 'GIG');    
insert into airport values ('SBGR', 'Guarulhos - Governador AndrÃ© Franco Montoro International Airport',  2459, 'GRU');    
insert into airport values ('SBSG', 'Governador AluÃ­zio Alves International Airport',  272, 'NAT');    
insert into airport values ('SBSP', 'Congonhas Airport',  2631, 'CGH');    
insert into airport values ('SBSV', 'Deputado Luiz Eduardo MagalhÃ£es International Airport',  64, 'SSA');    
insert into airport values ('SCEL', 'Comodoro Arturo Merino BenÃ­tez International Airport',  1555, 'SCL');    
insert into airport values ('SELT', 'Cotopaxi International Airport',  9205, 'LTX');    
insert into airport values ('SEQM', 'Mariscal Sucre International Airport',  7841, 'UIO');    
insert into airport values ('SKBO', 'El Dorado International Airport',  8361, 'BOG');    
insert into airport values ('SLVR', 'Viru Viru International Airport',  1224, 'VVI');    
insert into airport values ('SPIM', 'Jorge ChÃ¡vez International Airport',  113, 'LIM');    
insert into airport values ('SPZO', 'Alejandro Velasco Astete International Airport',  10860, 'CUZ');    
insert into airport values ('SUMU', 'Carrasco International /General C L Berisso Airport',  105, 'MVD');    
insert into airport values ('SVBC', 'General JosÃ© Antonio Anzoategui International Airport',  30, 'BLA');    
insert into airport values ('SVMI', 'SimÃ³n BolÃ­var International Airport',  234, 'CCS');    
insert into airport values ('TFFR', 'Pointe-Ã -Pitre Le Raizet',  36, 'PTP');    
insert into airport values ('TJSJ', 'Luis Munoz Marin International Airport',  9, 'SJU');    
insert into airport values ('TN-0002', 'Enfidha - Hammamet International Airport',  21, 'NBE');    
insert into airport values ('TNCM', 'Princess Juliana International Airport',  13, 'SXM');    
insert into airport values ('TR-0044', 'Ãukurova Airport',  15, '');    
insert into airport values ('UAAA', 'Almaty Airport',  2234, 'ALA');    
insert into airport values ('UACC', 'Astana International Airport',  1165, 'TSE');    
insert into airport values ('UAFM', 'Manas International Airport',  2058, 'FRU');    
insert into airport values ('UAKK', 'Sary-Arka Airport',  1765, 'KGF');    
insert into airport values ('UBBB', 'Heydar Aliyev International Airport',  10, 'GYD');    
insert into airport values ('UDYZ', 'Zvartnots International Airport',  2838, 'EVN');    
insert into airport values ('UGTB', 'Tbilisi International Airport',  1624, 'TBS');    
insert into airport values ('UHHH', 'Khabarovsk-Novy Airport',  244, 'KHV');    
insert into airport values ('UKBB', 'Boryspil International Airport',  427, 'KBP');    
insert into airport values ('UKFF', 'Simferopol International Airport',  639, 'SIP');    
insert into airport values ('UKHH', 'Kharkiv International Airport',  508, 'HRK');    
insert into airport values ('UKOO', 'Odessa International Airport',  172, 'ODS');    
insert into airport values ('ULLI', 'Pulkovo Airport',  78, 'LED');    
insert into airport values ('UMMS', 'Minsk National Airport',  670, 'MSQ');    
insert into airport values ('UNKL', 'Yemelyanovo Airport',  942, 'KJA');    
insert into airport values ('UNNT', 'Tolmachevo Airport',  365, 'OVB');    
insert into airport values ('URRP', 'Platov International Airport',  213, 'ROV');    
insert into airport values ('URSS', 'Sochi International Airport',  89, 'AER');    
insert into airport values ('USSS', 'Koltsovo Airport',  764, 'SVX');    
insert into airport values ('UTAA', 'Ashgabat International Airport',  692, 'ASB');    
insert into airport values ('UTTT', 'Tashkent International Airport',  1417, 'TAS');    
insert into airport values ('UUBW', 'Zhukovsky International Airport',  377, 'ZIA');    
insert into airport values ('UUDD', 'Domodedovo International Airport',  588, 'DME');    
insert into airport values ('UUEE', 'Sheremetyevo International Airport',  622, 'SVO');    
insert into airport values ('UUWW', 'Vnukovo International Airport',  685, 'VKO');    
insert into airport values ('UWKD', 'Kazan International Airport',  411, 'KZN');    
insert into airport values ('UWKG', 'Borisoglebskoye Airport',  213, '');    
insert into airport values ('UWUU', 'Ufa International Airport',  449, 'UFA');    
insert into airport values ('UWWW', 'Kurumoch International Airport',  477, 'KUF');    
insert into airport values ('VABB', 'Chhatrapati Shivaji International Airport',  39, 'BOM');    
insert into airport values ('VAGO', 'Dabolim Airport',  150, 'GOI');    
insert into airport values ('VCBI', 'Bandaranaike International Colombo Airport',  30, 'CMB');    
insert into airport values ('VCRI', 'Mattala Rajapaksa International Airport',  157, 'HRI');    
insert into airport values ('VDPP', 'Phnom Penh International Airport',  40, 'PNH');    
insert into airport values ('VDSR', 'Siem Reap International Airport',  60, 'REP');    
insert into airport values ('VECC', 'Netaji Subhash Chandra Bose International Airport',  16, 'CCU');    
insert into airport values ('VGZR', 'Hazrat Shahjalal International Airport',  30, 'DAC');    
insert into airport values ('VHHH', 'Hong Kong International Airport',  28, 'HKG');    
insert into airport values ('VIAR', 'Sri Guru Ram Dass Jee International Airport',  756, 'ATQ');    
insert into airport values ('VIDP', 'Indira Gandhi International Airport',  777, 'DEL');    
insert into airport values ('VMMC', 'Macau International Airport',  20, 'MFM');    
insert into airport values ('VNKT', 'Tribhuvan International Airport',  4390, 'KTM');    
insert into airport values ('VOBL', 'Kempegowda International Airport',  3000, 'BLR');    
insert into airport values ('VOCI', 'Cochin International Airport',  30, 'COK');    
insert into airport values ('VOCL', 'Calicut International Airport',  342, 'CCJ');    
insert into airport values ('VOHS', 'Rajiv Gandhi International Airport',  2024, 'HYD');    
insert into airport values ('VOMM', 'Chennai International Airport',  52, 'MAA');    
insert into airport values ('VOTV', 'Trivandrum International Airport',  15, 'TRV');    
insert into airport values ('VRMM', 'MalÃ© International Airport',  6, 'MLE');    
insert into airport values ('VTBD', 'Don Mueang International Airport',  9, 'DMK');    
insert into airport values ('VTBS', 'Suvarnabhumi Airport',  5, 'BKK');    
insert into airport values ('VTCC', 'Chiang Mai International Airport',  1036, 'CNX');    
insert into airport values ('VTSP', 'Phuket International Airport',  82, 'HKT');    
insert into airport values ('VVDN', 'Da Nang International Airport',  33, 'DAD');    
insert into airport values ('VVNB', 'Noi Bai International Airport',  39, 'HAN');    
insert into airport values ('VVTS', 'Tan Son Nhat International Airport',  33, 'SGN');    
insert into airport values ('VYMD', 'Mandalay International Airport',  300, 'MDL');    
insert into airport values ('VYYY', 'Yangon International Airport',  109, 'RGN');    
insert into airport values ('WAAA', 'Hasanuddin International Airport',  47, 'UPG');    
insert into airport values ('WADD', 'Ngurah Rai (Bali) International Airport',  14, 'DPS');    
insert into airport values ('WAJJ', 'Sentani International Airport',  289, 'DJJ');    
insert into airport values ('WARR', 'Juanda International Airport',  9, 'SUB');    
insert into airport values ('WAXX', 'Dominique Edward Osok Airport',  10, 'SOQ');    
insert into airport values ('WBSB', 'Brunei International Airport',  73, 'BWN');    
insert into airport values ('WIII', 'Soekarno-Hatta International Airport',  34, 'CGK');    
insert into airport values ('WIMM', 'Kualanamu International Airport',  23, 'KNO');    
insert into airport values ('WMKK', 'Kuala Lumpur International Airport',  69, 'KUL');    
insert into airport values ('WSSS', 'Singapore Changi Airport',  22, 'SIN');    
insert into airport values ('YBBN', 'Brisbane International Airport',  13, 'BNE');    
insert into airport values ('YMML', 'Melbourne International Airport',  434, 'MEL');    
insert into airport values ('YNT', 'Yantai Penglai International Airport',  154, 'YNT');    
insert into airport values ('YPAD', 'Adelaide International Airport',  20, 'ADL');    
insert into airport values ('YPPH', 'Perth International Airport',  67, 'PER');    
insert into airport values ('YSCB', 'Canberra International Airport',  1886, 'CBR');    
insert into airport values ('YSSY', 'Sydney Kingsford Smith International Airport',  21, 'SYD');    
insert into airport values ('ZBAA', 'Beijing Capital International Airport',  116, 'PEK');    
insert into airport values ('ZBAD', 'Beijing Daxing International Airport',  98, 'PKX');    
insert into airport values ('ZBHH', 'Baita International Airport',  3556, 'HET');    
insert into airport values ('ZBNY', 'Beijing Nanyuan Airport',  0, 'NAY');    
insert into airport values ('ZBTJ', 'Tianjin Binhai International Airport',  10, 'TSN');    
insert into airport values ('ZBYN', 'Taiyuan Wusu Airport',  2575, 'TYN');    
insert into airport values ('ZGGG', 'Guangzhou Baiyun International Airport',  50, 'CAN');    
insert into airport values ('ZGHA', 'Changsha Huanghua International Airport',  217, 'CSX');    
insert into airport values ('ZGKL', 'Guilin Liangjiang International Airport',  570, 'KWL');    
insert into airport values ('ZGNN', 'Nanning Wuxu Airport',  421, 'NNG');    
insert into airport values ('ZGSZ', 'Shenzhen Bao'an International Airport',  13, 'SZX');    
insert into airport values ('ZHCC', 'Zhengzhou Xinzheng International Airport',  495, 'CGO');    
insert into airport values ('ZHHH', 'Wuhan Tianhe International Airport',  113, 'WUH');    
insert into airport values ('ZJHK', 'Haikou Meilan International Airport',  75, 'HAK');    
insert into airport values ('ZJSY', 'Sanya Phoenix International Airport',  92, 'SYX');    
insert into airport values ('ZLXY', 'Xi'an Xianyang International Airport',  1572, 'XIY');    
insert into airport values ('ZMCK', 'Ulaanbaatar International Airport',  4482, 'UBN');    
insert into airport values ('ZMUB', 'Buyant-Ukhaa International Airport',  4364, 'ULN');    
insert into airport values ('ZPPP', 'Kunming Changshui International Airport',  6903, 'KMG');    
insert into airport values ('ZSAM', 'Xiamen Gaoqi International Airport',  59, 'XMN');    
insert into airport values ('ZSFZ', 'Fuzhou Changle International Airport',  46, 'FOC');    
insert into airport values ('ZSHC', 'Hangzhou Xiaoshan International Airport',  23, 'HGH');    
insert into airport values ('ZSJN', 'Yaoqiang Airport',  76, 'TNA');    
insert into airport values ('ZSNB', 'Ningbo Lishe International Airport',  13, 'NGB');    
insert into airport values ('ZSNJ', 'Nanjing Lukou Airport',  49, 'NKG');    
insert into airport values ('ZSPD', 'Shanghai Pudong International Airport',  13, 'PVG');    
insert into airport values ('ZSSS', 'Shanghai Hongqiao International Airport',  10, 'SHA');    
insert into airport values ('ZSWZ', 'Wenzhou Longwan International Airport',  0, 'WNZ');    
insert into airport values ('ZUCK', 'Chongqing Jiangbei International Airport',  1365, 'CKG');    
insert into airport values ('ZUGY', 'Longdongbao Airport',  3736, 'KWE');    
insert into airport values ('ZUUU', 'Chengdu Shuangliu International Airport',  1625, 'CTU');    
insert into airport values ('ZWWW', 'ÃrÃ¼mqi Diwopu International Airport',  2125, 'URC');    
insert into airport values ('ZYHB', 'Taiping Airport',  457, 'HRB');    
insert into airport values ('ZYTL', 'Zhoushuizi Airport',  107, 'DLC');    
insert into airport values ('ZYTX', 'Taoxian Airport',  198, 'SHE');    
